services:
  reverse-proxy:
    build:
      context: ./services/reverse-proxy
      dockerfile: Dockerfile
    restart: always
    volumes:
      - type: bind
        source: ./services/reverse-proxy/etc/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./services/reverse-proxy/etc/nginx/proxy_params.conf
        target: /etc/nginx/proxy_params.conf
    ports:
      - 8080:80
    depends_on:
      app:
        condition: service_healthy
  app:
    restart: always
    build:
      context: ./services/app
      target: dev
    volumes:
      - ./services/app/cmd:/usr/src/app/cmd
      - ./services/app/internal:/usr/src/app/internal
      - ./services/app/pkg:/usr/src/app/pkg
      - app-data:/data
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - ROOT_PATH=/data
      - MAX_UPLOAD_BYTES=1073741824 # 1GB
      - USAGE_CACHE_TTL=60
      - LOG_LEVEL=debug
      - PG_DB=app
      - PG_USER=admin
      - PG_PASSWORD=admin
      - PG_HOST=database
      - JWT_PRIVATE_KEY_PATH=jwt-private-key.pem
      - JWT_PUBLIC_KEY_PATH=jwt-public-key.pem
    healthcheck:
      test: ['CMD', './healthcheck']
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    depends_on:
      migrate:
        condition: service_completed_successfully
      file-storage:
        condition: service_healthy

  migrate:
    build:
      context: ./services/app
      target: dev
    command: chmod u+x ./db-migrate.sh && ./db-migrate.sh
    depends_on:
      database:
        condition: service_healthy

  file-storage:
    build:
      context: ./services/file-storage
    restart: always
    volumes:
      - file-storage-data:/data
    healthcheck:
      test: ['CMD', "curl", "-I", "http://localhost:8333/healthz"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  database:
    build:
      context: ./services/database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 5432:5432
volumes:
  app-data:
  db-data:
  file-storage-data: