services:
  reverse-proxy:
    build:
      context: ./services/reverse-proxy
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./services/reverse-proxy/.env
    volumes:
      - type: bind
        source: ./services/reverse-proxy/etc/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./services/reverse-proxy/etc/nginx/proxy_params.conf
        target: /etc/nginx/proxy_params.conf
    ports:
      - 8080:80
    depends_on:
      files:
        condition: service_healthy
  files:
    restart: always
    build:
      context: ./services/files
      target: dev
    volumes:
      - ./services/files/cmd:/usr/src/app/cmd
      - ./services/files/internal:/usr/src/app/internal
      - files-data:/data
    env_file:
      - ./services/files/.env
    healthcheck:
      test: ['CMD', './healthcheck']
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    depends_on:
      database:
        condition: service_healthy
      file-storage:
        condition: service_healthy

  file-storage:
    build:
      context: ./services/file-storage
    restart: always
    env_file:
      - ./services/file-storage/.env
    volumes:
      - file-storage-data:/data
    healthcheck:
      test: ['CMD', "curl", "-I", "http://localhost:8333/healthz"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  database:
    build:
      context: ./services/database
    restart: always
    env_file:
      - ./services/database/.env
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 30s
      retries: 5
      start_period: 20s
volumes:
  files-data:
  db-data:
  file-storage-data: