// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type ItemType string

const (
	ItemTypeFile      ItemType = "file"
	ItemTypeDirectory ItemType = "directory"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType
	Valid    bool // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

type Directory struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	ParentID uuid.NullUUID
	Name     string
	Location string
}

type DirectoryItem struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Type   ItemType
}

type File struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DirectoryID uuid.NullUUID
	Name        string
	Size        int32
	Location    string
}

type User struct {
	ID           uuid.UUID
	Name         string
	PasswordHash string
}
