// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const findDirectories = `-- name: FindDirectories :many
SELECT id, user_id, parent_id, name, location
FROM directories
`

func (q *Queries) FindDirectories(ctx context.Context) ([]Directory, error) {
	rows, err := q.db.QueryContext(ctx, findDirectories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Directory
	for rows.Next() {
		var i Directory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findDirectoryById = `-- name: FindDirectoryById :one
SELECT id, user_id, parent_id, name, location
FROM directories
WHERE id = $1
`

func (q *Queries) FindDirectoryById(ctx context.Context, id uuid.UUID) (Directory, error) {
	row := q.db.QueryRowContext(ctx, findDirectoryById, id)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Location,
	)
	return i, err
}

const findDirectoryByNameAndParentId = `-- name: FindDirectoryByNameAndParentId :one
SELECT id, user_id, parent_id, name, location
FROM directories
WHERE name = $1 AND parent_id IS NOT DISTINCT FROM $2
`

type FindDirectoryByNameAndParentIdParams struct {
	Name     string
	ParentID uuid.NullUUID
}

func (q *Queries) FindDirectoryByNameAndParentId(ctx context.Context, arg FindDirectoryByNameAndParentIdParams) (Directory, error) {
	row := q.db.QueryRowContext(ctx, findDirectoryByNameAndParentId, arg.Name, arg.ParentID)
	var i Directory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Location,
	)
	return i, err
}

const findFileById = `-- name: FindFileById :one
SELECT id, user_id, directory_id, name, size, location, checksum
FROM files
WHERE id = $1
`

func (q *Queries) FindFileById(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRowContext(ctx, findFileById, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DirectoryID,
		&i.Name,
		&i.Size,
		&i.Location,
		&i.Checksum,
	)
	return i, err
}

const findFileByNameAndDirectoryId = `-- name: FindFileByNameAndDirectoryId :one
SELECT id, user_id, directory_id, name, size, location, checksum
FROM files
WHERE name = $1
AND directory_id IS NOT DISTINCT FROM $2
`

type FindFileByNameAndDirectoryIdParams struct {
	Name        string
	DirectoryID uuid.NullUUID
}

func (q *Queries) FindFileByNameAndDirectoryId(ctx context.Context, arg FindFileByNameAndDirectoryIdParams) (File, error) {
	row := q.db.QueryRowContext(ctx, findFileByNameAndDirectoryId, arg.Name, arg.DirectoryID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DirectoryID,
		&i.Name,
		&i.Size,
		&i.Location,
		&i.Checksum,
	)
	return i, err
}

const findFiles = `-- name: FindFiles :many
SELECT id, user_id, directory_id, name, size, location, checksum
FROM files
WHERE directory_id = $1
`

func (q *Queries) FindFiles(ctx context.Context, directoryID uuid.NullUUID) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, findFiles, directoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DirectoryID,
			&i.Name,
			&i.Size,
			&i.Location,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFilesByLocation = `-- name: FindFilesByLocation :many
SELECT id, user_id, directory_id, name, size, location, checksum
FROM files
WHERE location LIKE $1 || '%'
`

func (q *Queries) FindFilesByLocation(ctx context.Context, dollar_1 sql.NullString) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, findFilesByLocation, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DirectoryID,
			&i.Name,
			&i.Size,
			&i.Location,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByName = `-- name: FindUserByName :one
SELECT id, name, password_hash
FROM users
WHERE name = $1
`

func (q *Queries) FindUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByName, name)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.PasswordHash)
	return i, err
}

const listDirectoryItems = `-- name: ListDirectoryItems :many
SELECT id, name, user_id, 'directory' AS type
FROM directories d
WHERE d.location = $1
UNION
SELECT id, name, user_id, 'file' AS type
FROM files f
WHERE f.location = $1
`

type ListDirectoryItemsRow struct {
	ID     uuid.UUID
	Name   string
	UserID uuid.UUID
	Type   string
}

func (q *Queries) ListDirectoryItems(ctx context.Context, location string) ([]ListDirectoryItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDirectoryItems, location)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectoryItemsRow
	for rows.Next() {
		var i ListDirectoryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDirectoryItem = `-- name: RemoveDirectoryItem :exec
DELETE FROM directory_items
WHERE id = $1 AND type = 'directory'
`

func (q *Queries) RemoveDirectoryItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeDirectoryItem, id)
	return err
}

const removeDirectoryRows = `-- name: RemoveDirectoryRows :execrows
DELETE FROM directories WHERE id = $1
`

func (q *Queries) RemoveDirectoryRows(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeDirectoryRows, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeFileItem = `-- name: RemoveFileItem :exec
DELETE FROM directory_items
WHERE id = $1 AND type = 'file'
`

func (q *Queries) RemoveFileItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeFileItem, id)
	return err
}

const removeFileRows = `-- name: RemoveFileRows :execrows
DELETE FROM files WHERE id = $1
`

func (q *Queries) RemoveFileRows(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeFileRows, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeUserRows = `-- name: RemoveUserRows :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) RemoveUserRows(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeUserRows, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveDirectory = `-- name: SaveDirectory :exec
INSERT INTO directories(id, user_id, parent_id, name, location)
VALUES($1, $2, $3, $4, $5)
ON CONFLICT(id)
DO UPDATE SET
	user_id = EXCLUDED.user_id,
	parent_id = EXCLUDED.parent_id,
	name = EXCLUDED.name,
	location = EXCLUDED.location
`

type SaveDirectoryParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	ParentID uuid.NullUUID
	Name     string
	Location string
}

func (q *Queries) SaveDirectory(ctx context.Context, arg SaveDirectoryParams) error {
	_, err := q.db.ExecContext(ctx, saveDirectory,
		arg.ID,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.Location,
	)
	return err
}

const saveDirectoryItem = `-- name: SaveDirectoryItem :exec
INSERT INTO directory_items(id, user_id, type)
VALUES($1, $2, 'directory')
ON CONFLICT(id)
DO NOTHING
`

type SaveDirectoryItemParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SaveDirectoryItem(ctx context.Context, arg SaveDirectoryItemParams) error {
	_, err := q.db.ExecContext(ctx, saveDirectoryItem, arg.ID, arg.UserID)
	return err
}

const saveFile = `-- name: SaveFile :exec
INSERT INTO files(id, user_id, directory_id, name, size, location, checksum)
VALUES($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT(id)
DO UPDATE SET
	user_id = EXCLUDED.user_id,
	directory_id = EXCLUDED.directory_id,
	name = EXCLUDED.name,
	size = EXCLUDED.size,
	location = EXCLUDED.location
`

type SaveFileParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	DirectoryID uuid.NullUUID
	Name        string
	Size        int32
	Location    string
	Checksum    string
}

func (q *Queries) SaveFile(ctx context.Context, arg SaveFileParams) error {
	_, err := q.db.ExecContext(ctx, saveFile,
		arg.ID,
		arg.UserID,
		arg.DirectoryID,
		arg.Name,
		arg.Size,
		arg.Location,
		arg.Checksum,
	)
	return err
}

const saveFileItem = `-- name: SaveFileItem :exec
INSERT INTO directory_items(id, user_id, type)
VALUES($1, $2, 'file')
ON CONFLICT(id)
DO NOTHING
`

type SaveFileItemParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SaveFileItem(ctx context.Context, arg SaveFileItemParams) error {
	_, err := q.db.ExecContext(ctx, saveFileItem, arg.ID, arg.UserID)
	return err
}

const saveUser = `-- name: SaveUser :exec
INSERT INTO users(id, name, password_hash)
VALUES($1, $2, $3)
ON CONFLICT(id)
DO UPDATE SET
name = EXCLUDED.name
`

type SaveUserParams struct {
	ID           uuid.UUID
	Name         string
	PasswordHash string
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) error {
	_, err := q.db.ExecContext(ctx, saveUser, arg.ID, arg.Name, arg.PasswordHash)
	return err
}
